spring:
  application:
    name: WMS_APP # ==> This is Service-Id

---
# profile for dev when using local service
spring:
  profiles: dev_local
eureka:
  instance:
    appname: WMS_APP
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://207.148.121.185:9000/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
#only update here
config:
    url:
      service: http://139.180.211.6:8080/WMS_Webservices/services/
      login : http://139.180.211.6:8080/WMS_Webservices/login
      token : http://139.180.211.6:8080/WMS_Webservices/oauth/token?grant_type=password&username=@username&password=@password
#      service: http://localhost:8080/WMS_Webservices/services/
#      login : http://localhost:8080/WMS_Webservices/login
#      token : http://localhost:8080/WMS_Webservices/oauth/token?grant_type=password&username=@username&password=@password
      upload: F:\Projects\WMS\temp\uploaded_file\
      template: F:\x8Store\source\WMS\src\main\resources\file_template\
      temp: F:\x8Store\source\WMS\src\main\resources\file_template\
server:
  port: 8020
---
# profile for dev when using clould service
spring:
  profiles: dev_service
eureka:
  instance:
    appname: WMS_APP
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://207.148.121.185:9000/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
config:
    url:
      upload: //WMS//uploaded_file//
      template : file_template/
      temp: D:\\WMS\\temp
server:
  port: 8020


#============== profiles for product environment===============
# don't update in dev environment
---
spring:
  profiles: prod
eureka:
  instance:
    appname: WMS_APP
    hostname: 207.148.121.185
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 5
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://207.148.121.185:9000/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
config:
    url:
      upload : //WMS//uploaded_file//
      template : //WMS//template//
      temp: //WMS//temp//
server:
  port: 8020
#
#ping-server:
#  ribbon:
#    eureka:
#      enabled: false # Disable Default Ping
#    listOfServers: 45.32.103.51:8082,45.32.103.51:8080
#    ServerListRefreshInterval: 10000