spring:
  application:
    name: WMS_APP # ==> This is Service-Id

---
# profile for dev when using local service
spring:
  profiles: cus_prod
eureka:
  instance:
    appname: WMS_APP
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://207.148.121.185:9000/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
#only update here
config:
  security:
       token: d2d492bb9cf31d41ed0f86ba9a7df10a2b2e9cda6fb0925bd6995d245ea99616
  url:
    service: hhttp://139.180.211.6:8080/WMS_Webservices/services/
    login : http://139.180.211.6:8080/WMS_Webservices/login
    token : http://139.180.211.6:8080/WMS_Webservices/oauth/token?grant_type=password&username=@username&password=@password
#    service: http://localhost:8888/WMS_Webservices_war/services/
#    login : http://localhost:8888/WMS_Webservices_war/login
#    token : http://localhost:8888/WMS_Webservices_war/oauth/token?grant_type=password&username=@username&password=@password
    template : F:\\Projects\WMS\temp\\file_template\\
    temp : F:\\Projects\\WMS\\temp\\
    upload:
server:
  port: 8020
